// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpPjt-iLm2vMJ5jR8p6Tc45KWgLlylrfc',
    appId: '1:396207908048:web:0657b6cbade643f59b2ad5',
    messagingSenderId: '396207908048',
    projectId: 'caribeasiswa-cabe',
    authDomain: 'caribeasiswa-cabe.firebaseapp.com',
    storageBucket: 'caribeasiswa-cabe.firebasestorage.app',
    measurementId: 'G-9M8KK5Z4QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvCOzukt-W1E5s_5mK6mMw4Mlx9fIhMF0',
    appId: '1:396207908048:android:d9283297a44055a69b2ad5',
    messagingSenderId: '396207908048',
    projectId: 'caribeasiswa-cabe',
    storageBucket: 'caribeasiswa-cabe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoB4llwRkg0et4_Ngf5X8BoCSkK84SPjo',
    appId: '1:396207908048:ios:ef4046272af38c849b2ad5',
    messagingSenderId: '396207908048',
    projectId: 'caribeasiswa-cabe',
    storageBucket: 'caribeasiswa-cabe.firebasestorage.app',
    iosBundleId: 'com.example.cabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoB4llwRkg0et4_Ngf5X8BoCSkK84SPjo',
    appId: '1:396207908048:ios:ef4046272af38c849b2ad5',
    messagingSenderId: '396207908048',
    projectId: 'caribeasiswa-cabe',
    storageBucket: 'caribeasiswa-cabe.firebasestorage.app',
    iosBundleId: 'com.example.cabe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpPjt-iLm2vMJ5jR8p6Tc45KWgLlylrfc',
    appId: '1:396207908048:web:54666cb49c9d67469b2ad5',
    messagingSenderId: '396207908048',
    projectId: 'caribeasiswa-cabe',
    authDomain: 'caribeasiswa-cabe.firebaseapp.com',
    storageBucket: 'caribeasiswa-cabe.firebasestorage.app',
    measurementId: 'G-2YJKXYHPKN',
  );
}
